services:
  - type: web
    name: ai-pdf-companion
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false # Set this in the Render dashboard for security
      - key: HUGGINGFACE_API_KEY
        sync: false # Set this in the Render dashboard for security
      - key: NEXT_PUBLIC_APP_URL
        sync: false # Will be set automatically by Render
    autoDeploy: true
    branch: main
    rootDir: .
    healthCheckPath: / 